# Generated by Django 3.0.6 on 2020-10-29 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('set', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('D', 'Damaged'), ('HP', 'Heavily Played'), ('MP', 'Moderately Played'), ('LP', 'Lightly Played'), ('NM', 'Near Mint')], default='NM', max_length=2)),
                ('author', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='upload/')),
                ('min_price', models.FloatField()),
                ('description', models.TextField(max_length=1024)),
                ('place_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=datetime.datetime(2020, 10, 30, 12, 50, 7, 831674, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('W', 'Wining'), ('L', 'Losing')], max_length=1)),
                ('expire', models.FloatField(default=0)),
                ('auct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
