# Generated by Django 3.0.6 on 2020-11-05 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('W', 'Wining'), ('L', 'Losing'), ('E', 'WON')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 21, 15, 0, 945256, tzinfo=utc)),
        ),
    ]
