# Generated by Django 3.0.6 on 2020-11-12 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_auto_20201105_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='life_cycle',
            field=models.CharField(choices=[('EX', 'exist'), ('BN', 'banned'), ('FN', 'finished')], default='EX', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 17, 7, 18, 39771, tzinfo=utc)),
        ),
    ]
